apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  namespace: default
spec:
  tls:
    - hosts:
        - ssemail.info
        - www.ssemail.info
      secretName: k8s-sslv-com
  rules:
    - host: ssemail.info
    - http:
        paths:
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000

    - host: www.ssemail.info
    - http:
        paths:
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service-b
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /graphql$1
spec:
  tls:
    - hosts:
        - ssemail.info
        - www.ssemail.info
      secretName: k8s-sslv-com
  rules:
    - host: ssemail.info
    - http:
        paths:
          - path: /api/graphql(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000

    - host: www.ssemail.info
    - http:
        paths:
          - path: /api/graphql(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
