apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
    - image: grusza/sslv-client
      context: ./client/
      sync:
        manual:
          - src: 'src/*'
            dest: .
      docker:
        dockerfile: ./Dockerfile.dev
    - image: grusza/sslv-server
      context: ./server/
      docker:
        dockerfile: ./Dockerfile.dev

deploy:
  kubectl:
    manifests:
      - ./k8_dev/*
