apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rewrite
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: / $1
  namespace: default

spec:
  rules:
     - http:
        paths:
          - backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
            path: /
          - backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
            path: /api(.*)
