apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1 break
  namespace: default

spec:
  rules:
     - http:
        paths:
          - backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000
            path: /

          - backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000
            path: /api/(.*)
