
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    namespace: default
spec:
  rules:
    - host: alex.sitdikov
    - http:
        paths:
          - path: /
            backend:
              serviceName: client-cluster-ip-service
              servicePort: 3000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service-b
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /graphql$1
spec:
  rules:
    - host: alex.sitdikov
    - http:
        paths:
          - path: /api/graphql(.*)
            backend:
              serviceName: server-cluster-ip-service
              servicePort: 5000