apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-sslv-com-tls
spec:
  secretName: k8s-sslv-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ssemail.info
  dnsNames:
    - ssemail.info
    - www.ssemail.info
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - ssemail.info
          - www.ssemail.info

            helm install \
            --set webhook.enabled=false \
            --name cert-manager \
            --namespace cert-manager \
            --version v0.8.0 \
            jetstack/cert-manager