sudo: required
services:
  - docker

before_install:
  - docker build -t grusza/sslv -f ./client/Dockerfile.dev ./client

script:
  - docker run grusza/sslv npm test

after_success:
  - docker build -t grusza/sslv-client ./client
  - docker build -t grusza/sslv-nginx ./nginx
  - docker build -t grusza/sslv-server ./server
  - docker build -t grusza/sslv-worker ./worker
  # Log in to  docker CLI
  - echo $DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker
  - docker push grusza/sslv-client
  - docker push grusza/sslv-nginx
  - docker push grusza/sslv-server
  - docker push grusza/sslv-worker


deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "sslv"
  env: "Sslv-env"
  bucket_name: "elasticbeanstalk-eu-central-1-868884770340"
  bucket_path: "sslv"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"